### ISSUE TITLE
Error: Couldn't find preset "env" relative to directory...

### ISSUE THREAD

**Issue by shiyuqi601** [whitedogg13/react-native-nfc-manager#53]
Hi, 
I am trying to test your example then I got this build error:

`error: bundling failed: Error: Couldn't find preset "env" relative to directory "/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/react-native-nfc-manager"
    at /home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/yuqi/code/react-native/Genu9/clients/react-native/node_modules/babel-core/lib/transformation/pipeline.js:46:16)`

I did `npm i --save react-native-nfc-manager`and `react-native link react-native-nfc-manager` successfully, but I didn't include `pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager/'` into the **Podfile**, because I can't find where it is. Does this **Podfile** have anything to do with the build error?

Thank you and forgive me if I ask a stupid question...

**Comment by whitedogg13** [comment]
Hi, thanks for reporting this! It's my bad, I have accidentally included the `.babelrc` (for library development/testing, not for publishing) into npm package.

I will publish a fixed version soon, for now, you can simply remove `.babelrc` in your `node_modules/react-native-nfc-manager`, then it should work!

Thanks

**Comment by whitedogg13** [comment]
Hi, I just published version `0.4.2`, this should fix previous issues. Thanks!

**Comment by shiyuqi601** [comment]
I have solved it by killing the server and restart it... then it works well! Thank you so much :)

**Comment by whitedogg13** [comment]
Great! It's good to help:)
